name: CD_Nginx
run-name: CD_Nginx

on:
  pull_request

permissions: write-all

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: build
        run: |
          docker login -u josemen97 -p ${{ secrets.TOKEN_DOCKER }}
          docker build . -t  josemen97/calculator
          docker push josemen97/calculator
